// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  agentSdkSidebar: [
    {
      type: 'category',
      label: 'Agent SDK',
      collapsible: true,
      collapsed: false,
      items: [
        'agent-sdk/overview',
        'agent-sdk/quickstart',
        'agent-sdk/compatible-features',
        'agent-sdk/message-lifecycle',
        'agent-sdk/context-window',
        'agent-sdk/converting-workflows',
      ],
    },
    {
      type: 'category',
      label: 'Setting permissions',
      collapsible: true,
      collapsed: true,
      items: [
        'setting-permissions/permission-modes',
        'setting-permissions/hooks',
        'setting-permissions/sandbox',
        'setting-permissions/checkpointing',
      ],
    },
    {
      type: 'category',
      label: 'Sending requests',
      collapsible: true,
      collapsed: true,
      items: [
        'sending-requests/streaming-queries',
        'sending-requests/individual-queries',
        'sending-requests/client-class',
        'sending-requests/subagents',
        'sending-requests/custom-prompts',
        'sending-requests/changing-models',
      ],
    },
    {
      type: 'category',
      label: 'Receiving responses',
      collapsible: true,
      collapsed: true,
      items: [
        'receiving-responses/approval-requests',
        'receiving-responses/user-questions',
        'receiving-responses/todo-lists',
        'receiving-responses/streaming-output',
        'receiving-responses/structured-output',
        'receiving-responses/error-handling',
      ],
    },
    {
      type: 'category',
      label: 'Persisting sessions',
      collapsible: true,
      collapsed: true,
      items: [
        'persisting-sessions/saving-restoring',
        'persisting-sessions/external-storage',
        'persisting-sessions/sharing-sessions',
        'persisting-sessions/subagent-sessions',
      ],
    },
    {
      type: 'category',
      label: 'Extending the SDK with custom tools',
      collapsible: true,
      collapsed: true,
      items: [
        'custom-tools/skills',
        'custom-tools/custom-tools',
        'custom-tools/slash-commands',
        'custom-tools/external-mcp',
        'custom-tools/embedded-mcp',
        'custom-tools/plugins',
        'custom-tools/tool-scaling',
        'custom-tools/troubleshooting-tools',
      ],
    },
    {
      type: 'category',
      label: 'Bundling the SDK in hosted applications',
      collapsible: true,
      collapsed: true,
      items: [
        'hosted-applications/production',
        'hosted-applications/cicd-pipelines',
        'hosted-applications/testing-evaluating',
        'hosted-applications/containerizing',
        'hosted-applications/credentials',
      ],
    },
    {
      type: 'category',
      label: 'Auditing usage',
      collapsible: true,
      collapsed: true,
      items: [
        'auditing/tracking-cost',
        'auditing/logs-telemetry',
        'auditing/sensitive-data',
        'auditing/identifying-users',
      ],
    },
    {
      type: 'category',
      label: 'TypeScript SDK reference',
      collapsible: true,
      collapsed: true,
      items: [
        'typescript-reference/ts-quickstart',
        'typescript-reference/ts-installation',
        'typescript-reference/ts-compilation',
        'typescript-reference/ts-query-function',
        'typescript-reference/ts-other-functions',
        {
          type: 'category',
          label: 'Types',
          collapsible: true,
          collapsed: true,
          items: [
            'typescript-reference/types/function-types',
            'typescript-reference/types/message-types',
            'typescript-reference/types/hook-types',
            'typescript-reference/types/tool-input-types',
            'typescript-reference/types/tool-output-types',
            'typescript-reference/types/permission-types',
            'typescript-reference/types/other-types',
          ],
        },
        'typescript-reference/ts-hooks',
        'typescript-reference/ts-sandbox',
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsible: true,
          collapsed: false,
          items: [
            'typescript-reference/troubleshooting/handling-slow-responses',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Python SDK reference',
      collapsible: true,
      collapsed: true,
      items: [
        'python-reference/py-quickstart',
        'python-reference/py-installation',
        'python-reference/py-query-function',
        'python-reference/py-client-class',
        'python-reference/py-other-functions',
        {
          type: 'category',
          label: 'Types',
          collapsible: true,
          collapsed: true,
          items: [
            'python-reference/types/py-function-types',
            'python-reference/types/py-message-types',
            'python-reference/types/py-hook-types',
            'python-reference/types/py-tool-input-types',
            'python-reference/types/py-tool-output-types',
            'python-reference/types/py-permission-types',
            'python-reference/types/py-other-types',
          ],
        },
        'python-reference/py-hooks',
        'python-reference/py-sandbox',
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsible: true,
          collapsed: false,
          items: [
            'python-reference/troubleshooting/py-handling-slow-responses',
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
